### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by uniqueum** [KiwiSkunk/APOD#2]
This is on a completely new setup... any ideas?
<img width="1440" alt="screeny" src="https://user-images.githubusercontent.com/38812169/150693409-81a97e03-ace2-4129-ac97-b79dda0ad78b.png">

**Comment by KiwiSkunk** [comment]
It appears you haven’t entered the api key. Have a read of the setup instructions as the api key is required.

**Comment by uniqueum** [comment]
Hi, nah, that's not it... my API key is in there alright, I just set it to XXX for the screeny so as to not share my key publicly...

**Comment by KiwiSkunk** [comment]
I few things I need to check: 
1/ you do have a folder called APOD inside the widgets folder?
2/ what OS version are you running?

Basically the issue is the data being returned from the bash script isn’t what is expected so it’s failing to split it into its components. 

you can email me privately at git@skunkworks.net.nz

**Comment by KiwiSkunk** [comment]
Closed. No further feedback. Updated since.
